# Generated by Django 2.0.9 on 2019-04-25 14:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingMobilityModel',
            fields=[
                ('meeting', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('track', models.CharField(default='', max_length=100)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolMobilityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StudentMobilityModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField()),
                ('classe', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('by_bike', models.BooleanField(default=True)),
                ('address_start', models.CharField(blank=True, max_length=200, null=True)),
                ('no_meeting', models.BooleanField(default=False)),
                ('custom_return', models.BooleanField(default=False)),
                ('modality_return', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_return', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_phone_return', models.CharField(blank=True, max_length=20, null=True)),
                ('meeting_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobilityday.MeetingMobilityModel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobilityday.SchoolMobilityModel')),
            ],
        ),
        migrations.CreateModel(
            name='TransportationMobilityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='studentmobilitymodel',
            name='transportation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mobilityday.TransportationMobilityModel'),
        ),
    ]
