# Generated by Django 2.0.9 on 2019-04-30 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobilityday', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmobilitymodel',
            name='meeting_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_return', to='mobilityday.MeetingMobilityModel'),
        ),
    ]
